### ISSUE TITLE
Background-image button bilan ustma ust bo`lib ketgan.

### ISSUE THREAD

**Issue by yuldoshevgg** [omon490/myteam-omon#9]
![image](https://user-images.githubusercontent.com/70746136/98925824-4bf88680-24f8-11eb-9363-9ac45c9aa700.png)

**Comment by omon490** [comment]
qaysi ekranda shunday bo'lyapti shuni aniqroq aytsangiz yahshi bo'lar edi

**Comment by yuldoshevgg** [comment]
329px

**Comment by omon490** [comment]
Rahmat to'g'irlandi)
